[controls.movement]
forwards = "SCROLL_UP"
backwards = "S"
left = "MOUSE_LEFT"   # testing
right = "MOUSE_RIGHT" # testing
speed_up = "SCROLL_UP"
speed_down = "SCROLL_DOWN"

[controls.sensitivity]
mouse_speed = 1.0
movement_speed = 1.0
